# Generated by Django 5.0.6 on 2024-07-13 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_product_sid_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sid',
        ),
    ]
